--script que reinicia la creacion de la PDB cuando ya fue creada con proyecto.sql
CONN / AS SYSDBA
SHOW USER
SHOW PDBS
ALTER PLUGGABLE DATABASE ORCLPDB1 CLOSE;
ALTER PLUGGABLE DATABASE PROJECT CLOSE;
DROP PLUGGABLE DATABASE PROJECT INCLUDING DATAFILES;